import { Tweet } from "@/types/tweets.types";

export const getMockTweet = (): Tweet => ({
  id: "1",
  userId: "user-1",
  content: "Hello, this is a mock tweet!",
  inReplyToTweetId: null,
  originalTweetId: null,
  mediaURLs: [],
  repliesCount: 0,
  likesCount: 0,
  retweetsCount: 0,
  viewsCount: 0,
  bookmarksCount: 0,
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
  isLiked: false,
  isRetweeted: false,
  isViewed: false,
  isBookmarked: false,
  user: {
    id: "user-1",
    username: "mockuser",
    displayName: "Mock User",
    email: "mock@user.com",
    isVerified: false,
    followers: [],
    following: [],
    avatarURL: "",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  replyTo: null,
  replies: null,
  thread: null,
  retweetedTweet: null,
  quotedTweet: null,
});
